# Практическая работа №2
**Тема:** Использование библиотеки Pandas
**ФИО:** _______________________
**Номер группы:** _______________________

### Шаг 1. Импорт библиотеки Pandas

In [64]:
import pandas as pd

### Шаг 2. Загрузка набора данных BlackFriday.csv

In [65]:
# Загрузите датасет при помощи read_csv()
df = pd.read_csv('BlackFriday.csv')

### Шаг 3. Первичный анализ данных
Посмотрите первые 10 строк данных и иную информацию о наборе данных при помощи shape, info и describe.

In [66]:
# Вывод первых 10 строк
df.head(10)

,User_ID,Product_ID,Gender,Age,Occupation,City_Category,Stay_In_Current_City_Years,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
0,1000001,P00069042,F,0-17,10,A,2,0,3,NaN,NaN,8370
1,1000001,P00248942,F,0-17,10,A,2,0,1,6.0,14.0,15200
2,1000001,P00087842,F,0-17,10,A,2,0,12,NaN,NaN,1422
3,1000001,P00085442,F,0-17,10,A,2,0,12,14.0,NaN,1057
4,1000002,P00285442,M,55+,16,C,4+,0,8,NaN,NaN,7969
5,1000003,P00193542,M,26-35,15,A,3,0,1,2.0,NaN,15227
6,1000004,P00184942,M,46-50,7,B,2,1,1,8.0,17.0,19215
7,1000004,P00346142,M,46-50,7,B,2,1,1,15.0,NaN,15854
8,1000004,P0097242,M,46-50,7,B,2,1,1,16.0,NaN,15686
9,1000005,P00274942,M,26-35,20,A,1,1,8,NaN,NaN,7871

In [67]:
# Вывод размера датасета
df.shape

(537577, 12)

In [68]:
# Вывод общей информации о столбцах и типах данных
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 537577 entries, 0 to 537576
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   User_ID                     537577 non-null  int64
 1   Product_ID                  537577 non-null  object
 2   Gender                      537577 non-null  object
 3   Age                         537577 non-null  object
 4   Occupation                  537577 non-null  int64
 5   City_Category               537577 non-null  object
 6   Stay_In_Current_City_Years  537577 non-null  object
 7   Marital_Status              537577 non-null  int64
 8   Product_Category_1          537577 non-null  int64
 9   Product_Category_2          370591 non-null  float64
 10  Product_Category_3          164278 non-null  float64
 11  Purchase                    537577 non-null  int64
dtypes: float64(2), int64(5), object(5)
memory usage: 49.2+ MB

In [69]:
# Вывод основных статистических характеристик
df.describe()

,User_ID,Occupation,Marital_Status,Product_Category_1,Product_Category_2,Product_Category_3,Purchase
count,5.375770e+05,537577.00000,537577.000000,537577.000000,370591.000000,164278.000000,537577.000000
mean,1.002992e+06,8.08271,0.408797,5.295546,9.842144,12.669840,9333.859853
std,1.714393e+03,6.52412,0.491612,3.750701,5.087259,4.124341,4981.022133
min,1.000001e+06,0.00000,0.000000,1.000000,2.000000,3.000000,185.000000
25%,1.001495e+06,2.00000,0.000000,1.000000,5.000000,9.000000,5866.000000
50%,1.003031e+06,7.00000,0.000000,5.000000,9.000000,14.000000,8062.000000
75%,1.004417e+06,14.00000,1.000000,8.000000,15.000000,16.000000,12073.000000
max,1.006040e+06,20.00000,1.000000,18.000000,18.000000,18.000000,23961.000000

### Шаг 4. Описание набора данных
*(Опишите набор данных своими словами в этой текстовой ячейке)*

## Раздел: Задания для выполнения (Таски)

### Таск 1. Сколько всего возрастных категорий?

In [70]:
df['Age'].nunique()

7

### Таск 2. Сколько строк с мужчинами из категории города А?

In [71]:
df[(df['Gender'] == 'M') & (df['City_Category'] == 'A')]['Gender'].count()

np.int64(109831)

### Таск 3. Сколько женщин от 46 до 50, потративших больше 20000?

In [72]:
df[(df['Gender'] == 'F') & (df['Age'] == '46-50') & (df['Purchase'] > 20000)]['Gender'].count()

np.int64(270)

### Таск 4. Сколько пропущенных значений в столбце Product_Category_3?

In [73]:
summ = df['Product_Category_3'].isna().sum()

print(summ)

373299

### Таск 5. Какую долю от всех покупателей составляют вместе мужчины от 26 до 35 лет и женщины старше 36 лет?

In [74]:
# 1. Фильтруем данные (указываем точные текстовые диапазоны для возраста)
typedata = df[((df['Gender'] == 'M') & (df['Age'] == '26-35')) | 
              ((df['Gender'] == 'F') & (df['Age'].isin(['36-45', '46+'])))]

# 2. Считаем долю через длину датафреймов (так как typedata — это уже отфильтрованная таблица)
share = len(typedata) / len(df)
percentage = share * 100

# 3. Выводим результат (исправил также букву f перед строкой в вашем принте)
print(f"Доля: {share:.4f}")
print(f"В процентах: {percentage:.2f}%")

Доля: 0.3567
В процентах: 35.67%